# Build stage

FROM docker.io/node:lts-alpine AS build

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4000

# Set the working directory
WORKDIR /app

RUN addgroup --system web && \
        adduser --system -G web web

COPY package.json pnpm-lock.yaml ./
RUN chown -R web:web .

RUN apk add --no-cache python3 make g++
RUN npx pnpm i --unsafe-perm

COPY . .
RUN npx pnpm run build:web

# Production stage

FROM docker.io/node:lts-alpine

WORKDIR /app

RUN addgroup --system web && \
        adduser --system -G web web

COPY --from=build /app/dist/apps/web ./web
COPY package.json pnpm-lock.yaml ./

RUN chown -R web:web .

RUN apk add --no-cache python3 make g++
RUN npx pnpm i --prod --unsafe-perm

EXPOSE 4000

CMD [ "npx", "vite", "preview" ]