
ARG NODE_VERSION=20.11.1

# Use an official Node.js runtime as a base image
FROM node:${NODE_VERSION}-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.json
COPY package.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN npm install --force

# Copy the rest of your app's source code
COPY . .

# Build the web app specifically
# Adjust the build command according to your package.json scripts
RUN npm run build:web

# Use Caddy as a base image
FROM caddy:2-alpine

# Copy the nginx configuration file
COPY ./apps/web/Caddyfile /etc/caddy/Caddyfile

# Copy the built app to the nginx serve directory
COPY --from=builder /app/dist/apps/web /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Caddy will automatically start serving the app
